/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentation;

import Core.UIManager;
import Services.AuthenticationService;

/**
 *
 * @author MohamedGaber
 */
public class DashboardWindow extends javax.swing.JPanel {
    private final AuthenticationService _authService;
    /**
     * Creates new form Home
     */
    public DashboardWindow() {
        initComponents();
        _authService = new AuthenticationService();
        currentUserBtn.setText(AuthenticationService.currentUser.Username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NavigatorPanel = new javax.swing.JPanel();
        NavBtn_Exports = new javax.swing.JButton();
        NavBtn_Imports = new javax.swing.JButton();
        NavBtn_Suppliers = new javax.swing.JButton();
        NavBtn_Inventory = new javax.swing.JButton();
        NavBtn_Customers = new javax.swing.JButton();
        NavBtn_Users = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        NavBtn_Home = new javax.swing.JButton();
        topBarPanel = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        currentUserBtn = new javax.swing.JButton();
        dashboardRouterPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(199, 197, 197));
        setForeground(new java.awt.Color(255, 255, 255));
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        setMaximumSize(new java.awt.Dimension(1200, 680));
        setMinimumSize(new java.awt.Dimension(1200, 680));
        setPreferredSize(new java.awt.Dimension(1200, 680));

        NavigatorPanel.setBackground(new java.awt.Color(144, 138, 138));
        NavigatorPanel.setPreferredSize(new java.awt.Dimension(300, 680));

        NavBtn_Exports.setBackground(new java.awt.Color(153, 153, 153));
        NavBtn_Exports.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NavBtn_Exports.setForeground(new java.awt.Color(255, 255, 255));
        NavBtn_Exports.setText("Exports");
        NavBtn_Exports.setAlignmentY(0.0F);
        NavBtn_Exports.setBorder(null);
        NavBtn_Exports.setMargin(new java.awt.Insets(0, 0, 0, 0));
        NavBtn_Exports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NavBtn_ExportsActionPerformed(evt);
            }
        });

        NavBtn_Imports.setBackground(new java.awt.Color(153, 153, 153));
        NavBtn_Imports.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NavBtn_Imports.setForeground(new java.awt.Color(255, 255, 255));
        NavBtn_Imports.setText("Imports");
        NavBtn_Imports.setAlignmentY(0.0F);
        NavBtn_Imports.setBorder(null);
        NavBtn_Imports.setMargin(new java.awt.Insets(0, 0, 0, 0));
        NavBtn_Imports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NavBtn_ImportsActionPerformed(evt);
            }
        });

        NavBtn_Suppliers.setBackground(new java.awt.Color(153, 153, 153));
        NavBtn_Suppliers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NavBtn_Suppliers.setForeground(new java.awt.Color(255, 255, 255));
        NavBtn_Suppliers.setText("Suppliers");
        NavBtn_Suppliers.setAlignmentY(0.0F);
        NavBtn_Suppliers.setBorder(null);
        NavBtn_Suppliers.setMargin(new java.awt.Insets(0, 0, 0, 0));
        NavBtn_Suppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NavBtn_SuppliersActionPerformed(evt);
            }
        });

        NavBtn_Inventory.setBackground(new java.awt.Color(153, 153, 153));
        NavBtn_Inventory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NavBtn_Inventory.setForeground(new java.awt.Color(255, 255, 255));
        NavBtn_Inventory.setText("Inventory");
        NavBtn_Inventory.setAlignmentY(0.0F);
        NavBtn_Inventory.setBorder(null);
        NavBtn_Inventory.setMargin(new java.awt.Insets(0, 0, 0, 0));
        NavBtn_Inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NavBtn_InventoryActionPerformed(evt);
            }
        });

        NavBtn_Customers.setBackground(new java.awt.Color(153, 153, 153));
        NavBtn_Customers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NavBtn_Customers.setForeground(new java.awt.Color(255, 255, 255));
        NavBtn_Customers.setText("Customers");
        NavBtn_Customers.setAlignmentY(0.0F);
        NavBtn_Customers.setBorder(null);
        NavBtn_Customers.setMargin(new java.awt.Insets(0, 0, 0, 0));
        NavBtn_Customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NavBtn_CustomersActionPerformed(evt);
            }
        });

        NavBtn_Users.setBackground(new java.awt.Color(153, 153, 153));
        NavBtn_Users.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NavBtn_Users.setForeground(new java.awt.Color(255, 255, 255));
        NavBtn_Users.setText("Staff");
        NavBtn_Users.setAlignmentY(0.0F);
        NavBtn_Users.setBorder(null);
        NavBtn_Users.setMargin(new java.awt.Insets(0, 0, 0, 0));
        NavBtn_Users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NavBtn_UsersActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        jLabel1.setToolTipText("");

        NavBtn_Home.setBackground(new java.awt.Color(153, 153, 153));
        NavBtn_Home.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NavBtn_Home.setForeground(new java.awt.Color(255, 255, 255));
        NavBtn_Home.setText("Home");
        NavBtn_Home.setAlignmentY(0.0F);
        NavBtn_Home.setBorder(null);
        NavBtn_Home.setMargin(new java.awt.Insets(0, 0, 0, 0));
        NavBtn_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NavBtn_HomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavigatorPanelLayout = new javax.swing.GroupLayout(NavigatorPanel);
        NavigatorPanel.setLayout(NavigatorPanelLayout);
        NavigatorPanelLayout.setHorizontalGroup(
            NavigatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigatorPanelLayout.createSequentialGroup()
                .addGroup(NavigatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NavigatorPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(NavBtn_Home, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NavBtn_Inventory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NavBtn_Suppliers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NavBtn_Imports, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NavBtn_Exports, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NavBtn_Customers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(NavBtn_Users, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        NavigatorPanelLayout.setVerticalGroup(
            NavigatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigatorPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(NavBtn_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(NavBtn_Inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(NavBtn_Suppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(NavBtn_Imports, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(NavBtn_Exports, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(NavBtn_Customers, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(NavBtn_Users, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        topBarPanel.setBackground(new java.awt.Color(144, 138, 138));
        topBarPanel.setPreferredSize(new java.awt.Dimension(0, 0));

        logoutBtn.setBackground(new java.awt.Color(203, 62, 80));
        logoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setText("Logout");
        logoutBtn.setBorder(null);
        logoutBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Female User-2.png"))); // NOI18N
        jLabel2.setToolTipText("");
        jLabel2.setPreferredSize(new java.awt.Dimension(32, 32));

        currentUserBtn.setBackground(new java.awt.Color(144, 138, 138));
        currentUserBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        currentUserBtn.setForeground(new java.awt.Color(255, 255, 255));
        currentUserBtn.setText("Username");
        currentUserBtn.setBorder(null);
        currentUserBtn.setBorderPainted(false);
        currentUserBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        currentUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentUserBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topBarPanelLayout = new javax.swing.GroupLayout(topBarPanel);
        topBarPanel.setLayout(topBarPanelLayout);
        topBarPanelLayout.setHorizontalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topBarPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        topBarPanelLayout.setVerticalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(topBarPanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        dashboardRouterPanel.setBackground(new java.awt.Color(199, 197, 197));
        dashboardRouterPanel.setAutoscrolls(true);
        dashboardRouterPanel.setName("dashboardRouterPanel"); // NOI18N

        javax.swing.GroupLayout dashboardRouterPanelLayout = new javax.swing.GroupLayout(dashboardRouterPanel);
        dashboardRouterPanel.setLayout(dashboardRouterPanelLayout);
        dashboardRouterPanelLayout.setHorizontalGroup(
            dashboardRouterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 894, Short.MAX_VALUE)
        );
        dashboardRouterPanelLayout.setVerticalGroup(
            dashboardRouterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(NavigatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(dashboardRouterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(topBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NavigatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(topBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dashboardRouterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        dashboardRouterPanel.getAccessibleContext().setAccessibleParent(dashboardRouterPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void NavBtn_ExportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavBtn_ExportsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NavBtn_ExportsActionPerformed

    private void NavBtn_ImportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavBtn_ImportsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NavBtn_ImportsActionPerformed

    private void NavBtn_SuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavBtn_SuppliersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NavBtn_SuppliersActionPerformed

    private void NavBtn_InventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavBtn_InventoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NavBtn_InventoryActionPerformed

    private void NavBtn_CustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavBtn_CustomersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NavBtn_CustomersActionPerformed

    private void NavBtn_UsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavBtn_UsersActionPerformed
        UIManager.Instance.GoToUsersListPage();
    }//GEN-LAST:event_NavBtn_UsersActionPerformed

    private void NavBtn_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavBtn_HomeActionPerformed
        UIManager.Instance.GoToHomePage();
    }//GEN-LAST:event_NavBtn_HomeActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        _authService.Logout();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void currentUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentUserBtnActionPerformed
        UIManager.Instance.GoToViewUserPage(AuthenticationService.currentUser.Id);
    }//GEN-LAST:event_currentUserBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NavBtn_Customers;
    private javax.swing.JButton NavBtn_Exports;
    private javax.swing.JButton NavBtn_Home;
    private javax.swing.JButton NavBtn_Imports;
    private javax.swing.JButton NavBtn_Inventory;
    private javax.swing.JButton NavBtn_Suppliers;
    private javax.swing.JButton NavBtn_Users;
    private javax.swing.JPanel NavigatorPanel;
    private javax.swing.JButton currentUserBtn;
    private javax.swing.JPanel dashboardRouterPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel topBarPanel;
    // End of variables declaration//GEN-END:variables
}
