/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentation;

import Core.UIManager;
import Services.AuthenticationService;

/**
 *
 * @author MohamedGaber
 */
public class LoginWindow extends javax.swing.JPanel {
    private final AuthenticationService _service;
    /**
     * Creates new form Login
     */
    public LoginWindow() {
        initComponents();
        _service = new AuthenticationService();
        ErrorMsg.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UsernameInput = new javax.swing.JTextField();
        UsernameLabel = new javax.swing.JLabel();
        PasswordInput = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        LoginBtn = new javax.swing.JButton();
        ErrorMsg = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(UsernameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 6, 237, 35));

        UsernameLabel.setText("Username");
        jPanel1.add(UsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 15, -1, -1));
        jPanel1.add(PasswordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 47, 237, 35));

        PasswordLabel.setText("Password");
        jPanel1.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 56, -1, -1));

        LoginBtn.setText("Login");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 116, 103, 36));

        ErrorMsg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ErrorMsg.setForeground(new java.awt.Color(255, 0, 0));
        ErrorMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ErrorMsg.setText("Here is an Error Message");
        jPanel1.add(ErrorMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 88, 326, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        System.out.println("Entered password = " +  PasswordInput.getText());
        String error = _service.Login(UsernameInput.getText(), PasswordInput.getText());
        
        if(error == null)
        {
            UIManager.Instance.LoadHomeWindow();
            return;
        }
        ErrorMsg.setText(error);
    }//GEN-LAST:event_LoginBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ErrorMsg;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JTextField PasswordInput;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JTextField UsernameInput;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
